// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnWP_QCz1D1Q77aLJc6L7KIno8y4UU2NY',
    appId: '1:572403602231:web:113dc1814be687025980b2',
    messagingSenderId: '572403602231',
    projectId: 'creathio-logisticapp',
    authDomain: 'creathio-logisticapp.firebaseapp.com',
    databaseURL: 'https://creathio-logisticapp-default-rtdb.firebaseio.com',
    storageBucket: 'creathio-logisticapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRVyuZ52Uc_o7yw9pmaJXljQbZstgSZXI',
    appId: '1:572403602231:android:0924ea7070b858305980b2',
    messagingSenderId: '572403602231',
    projectId: 'creathio-logisticapp',
    databaseURL: 'https://creathio-logisticapp-default-rtdb.firebaseio.com',
    storageBucket: 'creathio-logisticapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARPt03RZjOW9B09Ds2fBJ090FLqIRpw9Q',
    appId: '1:572403602231:ios:92fe931463d737dd5980b2',
    messagingSenderId: '572403602231',
    projectId: 'creathio-logisticapp',
    databaseURL: 'https://creathio-logisticapp-default-rtdb.firebaseio.com',
    storageBucket: 'creathio-logisticapp.appspot.com',
    iosClientId: '572403602231-4enc3t473rgsf666q45gqngvidmu3d49.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicoreFinalCut',
  );
}
